In [3]:
a = ("C", "O", "G", "H")
a

tuple

In [12]:
a = ["C", "O", "G", "H"]
a

['C', 'O', 'G', 'H']

In [23]:
a = ( 1 + 4, )
a

(5,)

In [18]:
a = [ 1 ]
type(a)

list

In [24]:
a = [1, 10.0, "MIDE", True]
a

[1, 10.0, 'MIDE', True]

In [41]:
a = tuple(a)
a[len(a)-1]

True

In [54]:
a[1:3]

(1, 10.0)

In [53]:
a

(1, 10.0, 'MIDE', True)

In [60]:
a = [2,"mide", 9.0, [3,4]]
b = a[:]
b[-1] = "HOLA"
b

[2, 'mide', 9.0, 'HOLA']

In [61]:
a

[2, 'mide', 9.0, [3, 4]]

In [64]:
b.append(1000)
b

[2, 'mide', 9.0, 'HOLA', 1000]

In [66]:
del b[-1]

In [67]:
b

[2, 'mide', 9.0, 'HOLA']

In [100]:
b = []

## Yo quiero poblar la lista con numeros de 0 al 9 
for i in range(11,20):
    b.append(i)

b

[11, 12, 13, 14, 15, 16, 17, 18, 19]

In [97]:
b[5]

16

In [98]:
del b[5]

In [99]:
b

[11, 12, 13, 14, 15, 17, 18, 19]

In [105]:
b.remove(16)
b

ValueError: list.remove(x): x not in list

In [130]:
if 18 in b:
    b.remove(18)
    print("Hola")

In [135]:
b = [5,2,1,7,84,196, 2 ,4]
b.sort()
b

[1, 2, 2, 4, 5, 7, 84, 196]

In [142]:
b = [3,4,5.0, "mide"]
b.sort()

TypeError: '<' not supported between instances of 'str' and 'float'

In [139]:
b.sort(reverse=True)
b

[196, 84, 7, 5, 4, 2, 2, 1]

In [141]:
b.reverse()
b

[1, 2, 2, 4, 5, 7, 84, 196]

In [145]:


b + c

[1, 2, 3, 4, 4, 5, 6, 7]

In [8]:
import numpy as np

b = [1,2,3,4]
c = [4,5,6,7]

b + c

[1, 2, 3, 4, 4, 5, 6, 7]

In [10]:
b = np.array(b)
c = np.array(c)

b * c

array([ 4, 10, 18, 28])

In [37]:
b = [
      [1,2,3], # Registro linea 1
      [4,5,6]  # Regrisrro linea 2
    ]
b = np.array(b)
b.shape

(2, 3)

In [28]:
b = [
    [1,2,3,4],
    [4,5,6,7]
]
b

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [38]:
import pandas as pd

df_b = pd.DataFrame(b, columns = ["A", "B", "C"])
df_b.shape

(2, 3)

In [47]:
df_b

   A  B  C
0  1  2  3
1  4  5  6

In [56]:
df_b.to_numpy?

Signature:
df_b.to_numpy(
    dtype: 'npt.DTypeLike | None' = None,
    copy: 'bool' = False,
    na_value: 'object' = <no_default>,
) -> 'np.ndarray'
Docstring:
Convert the DataFrame to a NumPy array.

By default, the dtype of the returned array will be the common NumPy
dtype of all types in the DataFrame. For example, if the dtypes are
``float16`` and ``float32``, the results dtype will be ``float32``.
This may require copying data and coercing values, which may be
expensive.

Parameters
----------
dtype : str or numpy.dtype, optional
    The dtype to pass to :meth:`numpy.asarray`.
copy : bool, default False
    Whether to ensure that the returned value is not a view on
    another array. Note that ``copy=False`` does not *ensure* that
    ``to_numpy()`` is no-copy. Rather, ``copy=True`` ensure that
    a copy is made, even if not strictly necessary.
na_value : Any, optional
    The value to use for missing values. The default value depends
    on `dtype` and the dtypes of the DataFrame columns.

Returns
-------
numpy.ndarray

See Also
--------
Series.to_numpy : Similar method for Series.

Examples
--------
>>> pd.DataFrame({"A": [1, 2], "B": [3, 4]}).to_numpy()
array([[1, 3],
       [2, 4]])

With heterogeneous data, the lowest common type will have to
be used.

>>> df = pd.DataFrame({"A": [1, 2], "B": [3.0, 4.5]})
>>> df.to_numpy()
array([[1. , 3. ],
       [2. , 4.5]])

For a mix of numeric and non-numeric types, the output array will
have object dtype.

>>> df['C'] = pd.date_range('2000', periods=2)
>>> df.to_numpy()
array([[1, 3.0, Timestamp('2000-01-01 00:00:00')],
       [2, 4.5, Timestamp('2000-01-02 00:00:00')]], dtype=object)
File:      ~/Documents/MIDE/diplomado_ciencia_datos_mide/.venv/lib/python3.11/site-packages/pandas/core/frame.py
Type:      method

In [54]:
df_b

   A  B  C
0  1  2  3
1  4  5  6

In [51]:
b = [1,2,3]
b.append(6)

In [67]:
from typing import Union
### Tipe hint

def modifica_lista(la_lista : list, valor : Union[int, float, bool]) -> None:
    """
    ## Documentacion
    La funcion agrega un valor al final de la lista.

    Argumentos:

    - la_lista :  list  ---> Es la lista a modificar
    - valor : Union[int, float, bool] ---> Valor a agregar a la lista

    Valor de regreso None
    """
    la_lista.append(valor)

b = [2,3,4,5]

k = modifica_lista(b, 102)

In [68]:
b

[2, 3, 4, 5, 102]

In [71]:
b = [1,2,3]
b.append(4)

In [79]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

    .. versionchanged:: 1.3.0

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
...                    columns=['a', 'b', 'c'])
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
>>> df3 = pd.DataFrame(data, columns=['c', 'a'])
...
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3
File:           ~/Documents/MIDE/diplomado_ciencia_datos_mide/.venv/lib/python3.11/site-packages/pandas/core/frame.py
Type:           type
Subclasses:     SubclassedDataFrame

In [82]:

def convierte_ndarray(una_lista):
    """
    Funcion convierte_lista_a_npndarray
    """
    return np.array(una_lista)

convierte_lista_a_npndarray(b)

array([1, 2, 3, 4])

In [66]:
convierte_lista_a_npndarray?

Signature: convierte_lista_a_npndarray(una_lista: list) -> numpy.ndarray
Docstring: Funcion convierte_lista_a_npndarray
File:      /tmp/ipykernel_211370/3316149647.py
Type:      function

In [116]:
datos = (
    (1,2,3),
    (4,5,6), 
    (7,8,8)
)

df_datos = pd.DataFrame(datos, columns = ["A", "B", "C"])
df_datos

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  8

In [115]:
df_datos["B"] = df_datos["B"]*6
df_datos

   A   B  C
0  1  12  3
1  4  30  6
2  7  48  8

In [118]:
pais_idioma = {
    "USA" : "ingles",
    "MEX" : "español", 
    "COL" : "español",
    "TUK" : "turco"
}

pais_pob = {
    "USA" : {
        "pob" : 200_000_000,
        "idioma" : "ingles"
    },
    "MEX" : 130_000_000, 
    "COL" : 60_000_000,
    "TUK" : 150_000_000
}
pais_pob

{'USA': 200000000, 'MEX': 130000000, 'COL': 60000000, 'TUK': 150000000}

In [124]:
df_datos = df_datos.rename(columns = {"B" : "B_NUEVA"})
df_datos

   A  B_NUEVA  C
0  1        2  3
1  4        5  6
2  7        8  8

In [126]:
df_datos.columns

Index(['A', 'B_NUEVA', 'C'], dtype='object')

In [132]:
import json

pais_idioma

{'USA': 'ingles', 'MEX': 'español', 'COL': 'español', 'TUK': 'turco'}