# Sesión 2

In [11]:
## Una lista
x = [2,3, "3", 2.3]
x

[2, 3, '3', 2.3]

In [12]:
x[0]

2

In [3]:
## Tupla
x = (1,2, "3", 4.5)
x

(1, 2, '3', 4.5)

In [5]:
## Conjunto
x = {1,2, "3", 4.5}
x

{1, 2, '3', 4.5}

In [18]:
## Un diccionario
diccionario = {
    "red" : "rojo",
    "blue" : "azul", 
    "pink" : "rosa"
}

print(f"Cual es la traducción de pink en español? es {diccionario['pink']}")

Cual es la traducción de pink en español? es rosa

In [10]:
x['pink']

'rosa'

In [15]:
x = [1,2]
a,b = x

2

In [17]:
x = [(1, "a"),(2, "b"), (3, "c"),(4, "d"),(5, "e")]


for i,j in x: 
    print(i, j)

1 a
2 b
3 c
4 d
5 e

In [22]:
diccionario

{'red': 'rojo', 'blue': 'azul', 'pink': 'rosa'}

In [23]:
for llave,valor in diccionario.items():
    print(f"llave = {llave} y valor = {valor}")

llave = red y valor = rojo
llave = blue y valor = azul
llave = pink y valor = rosa

In [26]:
x = [(1, "a"),(2, "b"), (3, "c"),(4, "d"),(5, "e")]
dict(x)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e'}

In [31]:
if "orange" in diccionario:
    print(diccionario["orange"])
else:
    print("No cuento con la traduccion")
#diccionario["orange"]

No cuento con la traduccion

In [32]:
diccionario.get("orange", "No cuento con la traduccion")

'No cuento con la traduccion'

# Colecciones por compresión

In [33]:
x = [1,2,3,4]
x_cuadrada = []

for i in x:
    x_cuadrada.append(
        i*i
    )
x_cuadrada

[1, 4, 9, 16]

In [39]:
[i*i for i in x if i>2]

[9, 16]

In [47]:
### Usemos un diccionario para almacenar la nómina de los empleados
empleados = {
    "Alice" : 1_000_000,
    "Bob" : 998_671,
    "Carol" : 122_908,
    "Frank" : 88_123, 
    "Eve" : 93_121
}
## Genera un nuevo diccionario que contenga sólo los empleados que ganen arriba de 100_000
nuevo_diccionario = {empleado : salario for empleado, salario in empleados.items() if salario > 100_000}
nuevo_diccionario

## Genera una lista que contenga los nombres de los empleados que ganen arriba de 100_00
nombre_empleados = [empleado for empleado, salario in empleados.items() if salario > 100_000]
nombre_empleados

['Alice', 'Bob', 'Carol']

In [51]:
#### Genera un diccionario que contenga la compensación del 10% del salario para cada empleado
tasa_compensacion = 0.10
{empleado : salario + round(salario*tasa_compensacion,1)  for empleado, salario in empleados.items() if salario > 100_000}

{'Alice': 1100000.0, 'Bob': 1098538.1, 'Carol': 135198.8}

In [54]:
def compensacion_total(salario, tasa, precision):
    return round(salario+(salario*tasa),precision)

{empleado : compensacion_total(salario, tasa_compensacion, 1) for empleado, salario in empleados.items() if salario > 100_000}

{'Alice': 1100000.0, 'Bob': 1098538.1, 'Carol': 135198.8}

In [66]:
df_empleados_compensa = df_empleados.query("salario > 100_000")

df_empleados_compensa["ingreso_total"] = df_empleados_compensa["salario"].apply( 
    lambda salario : salario + (salario * tasa_compensacion)
)
df_empleados_compensa

  empleado  salario  ingreso_total
0    Alice  1000000      1100000.0
1      Bob   998671      1098538.1
2    Carol   122908       135198.8

In [59]:
import pandas as pd

df_empleados = pd.DataFrame(
    {
        "empleado" : empleados.keys(), 
        "salario" : empleados.values()
    }
)

df_empleados

  empleado  salario
0    Alice  1000000
1      Bob   998671
2    Carol   122908
3    Frank    88123
4      Eve    93121

In [69]:
df_empleados.dtypes

empleado      str
salario     int64
dtype: object

In [68]:
import polars as pl

df_empleados_pl = pl.from_pandas(df_empleados)
df_empleados_pl

shape: (5, 2)
┌──────────┬─────────┐
│ empleado ┆ salario │
│ ---      ┆ ---     │
│ str      ┆ i64     │
╞══════════╪═════════╡
│ Alice    ┆ 1000000 │
│ Bob      ┆ 998671  │
│ Carol    ┆ 122908  │
│ Frank    ┆ 88123   │
│ Eve      ┆ 93121   │
└──────────┴─────────┘

In [73]:
df_empleados_pl.filter(
    pl.col("salario") > 100_000
).with_columns(
    ingreso_total = pl.col("salario") + (pl.col("salario") * tasa_compensacion)
)

shape: (3, 3)
┌──────────┬─────────┬───────────────┐
│ empleado ┆ salario ┆ ingreso_total │
│ ---      ┆ ---     ┆ ---           │
│ str      ┆ i64     ┆ f64           │
╞══════════╪═════════╪═══════════════╡
│ Alice    ┆ 1000000 ┆ 1.1e6         │
│ Bob      ┆ 998671  ┆ 1098538.1     │
│ Carol    ┆ 122908  ┆ 135198.8      │
└──────────┴─────────┴───────────────┘

In [75]:
import numpy as np 

x = np.array([1,2,3,4])

x*2

array([2, 4, 6, 8])